#!/bin/bash

# Nome del file CSV
csv_file="/home/chicco/Downloads/database.csv"

# Nome del database SQLite
db_file="/home/chicco/database.db"

# Nome della tabella nel database
table_name="tua_tabella"

if [ ! -f "$db_file" ]; then
    sqlite3 "$db_file" "CREATE TABLE $table_name (
        nome_casa TEXT,
        codice_casa TEXT,
        tipo_alloggio TEXT,
        tipo_locazione TEXT,
        codice_regione TEXT,
        città TEXT,
        cap TEXT,
        paese TEXT,
        indirizzo TEXT,
        numero TEXT
    );"
fi

# Importare i dati dal CSV nella tabella
sqlite3 "$db_file" <<EOF
.mode csv
.separator ","
.import $csv_file $table_name
EOF

echo "Importazione completata."